### ISSUE TITLE
I dont get it

### ISSUE THREAD

**Issue by KrusteDE** [JonasHeim/Civilization-5-Savegame-Editor#1]
I dont know how to use your programm or what i have to do. Should i start your programm with Windows Powershell or just start it? I just get: Choose Application, but i cant choose anything.

**Comment by emmehan** [comment]
Hi, basically it is just a .Net application that runs as a standalone.
So you can either compile it yourself or download the release 0.0.1 .zip file and run the .exe.

**Comment by KrusteDE** [comment]
Which .exe? from civ 5 or your programm or both ?

**Comment by emmehan** [comment]
Hi,
run the .exe from the release and open up your multiplayer savegame file. You can change the gamemode of that savefile from multiplayer to singleplayer and vice versa.
Once the savefile is set to singleplayer, you can edit the game e.g. using an ingame editor (from Steam Workshop). 
When you are done editing change the gamemode back to multiplayer and continue playing with your friends.
I created this, because the ingame editor can only edit singleplayer savegames.

**Comment by emmehan** [comment]
Can this be closed?

**Comment by emmehan** [comment]
Closed.
