### ISSUE TITLE
Confused - Detailed instructions/tutorial please

### ISSUE THREAD

**Issue by CrippledJoe** [JonasHeim/Civilization-5-Savegame-Editor#3]
Hello, I have followed whatever instructions you have given so far but I am still very stuck and confused. Could you please help us by giving step by step instructions!:)

The .net downloaded does not enable my save editor to load anything up. It still asks to open with browse programs.

**Comment by emmehan** [comment]
Hi @CrippledJoe,

no problem.
I guess you have already downloaded the release - if not please do that [here](https://github.com/JonasHeim/Civilization-5-Savegame-Editor/releases/tag/v0.0.1).
Within the archive there are is a folder named Release. In there you will find the precompiled application **Civ5 Savegame Editor.exe** your are looking for.
You can open up your savegame in this application and change the gametype - from Singleplayer to Multiplayer vice versa.

I created this tool to be able to quickly switch between the game types because other tools/mods like the [IngameEditor](https://forums.civfanatics.com/threads/ingame-editor.436912/) can only edit Singleplay savegames.

I hope this helps :)
